# src/helpers.py
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import os
import cohere

COHERE_API_KEY = "OBE5OhyoSiPZWTCGLik8c6jddpIrrVEEymyMYceA"  # replace with your actual Cohere API key
co = cohere.Client(COHERE_API_KEY)



# ----------------------
# CO2 Emission Calculation
# ----------------------
def calculate_emissions(gpu_name, hours, region, gpus_df=None, impact_df=None,
                        power_watts=None, gco2_per_kwh=None, pue=None):
    """
    Calculate CO2 emissions for a GPU/CPU training session.
    Allows input of custom device parameters if not in CSV.
    """
    try:
        # GPU info
        if power_watts is None:
            gpu_row = gpus_df[gpus_df['name'] == gpu_name].iloc[0]
            power_watts = gpu_row['power_watts']

        # Region info
        if gco2_per_kwh is None or pue is None:
            region_row = impact_df[impact_df['region'] == region].iloc[0]
            if gco2_per_kwh is None:
                gco2_per_kwh = region_row['gCO2_per_kWh']
            if pue is None:
                pue = region_row['pue']

        # Convert watts to kWh
        kwh = (power_watts * hours) / 1000
        emissions = kwh * gco2_per_kwh * pue
        return emissions

    except IndexError:
        return f"Error: Device '{gpu_name}' or region '{region}' not found."
    except Exception as e:
        return f"Error: {str(e)}"

def calculate_emissions_batch(devices, gpus_df=None, impact_df=None):
    """
    Calculate emissions for a list of devices.
    Each device is a dict with keys: gpu_name, hours, region, power_watts (optional), gco2_per_kwh (optional), pue (optional)
    Returns a list of emissions or error messages.
    """
    results = []
    for dev in devices:
        emissions = calculate_emissions(
            gpu_name=dev.get('gpu_name'),
            hours=dev.get('hours'),
            region=dev.get('region'),
            gpus_df=gpus_df,
            impact_df=impact_df,
            power_watts=dev.get('power_watts'),
            gco2_per_kwh=dev.get('gco2_per_kwh'),
            pue=dev.get('pue')
        )
        results.append(emissions)
    return results


def ai_recommendations_cohere(emissions, gpu_name, hours, region, api_key):
    """
    Generate AI-based carbon footprint reduction recommendations using Cohere.
    Returns the full text generated by the model.
    """
    co = cohere.Client(api_key)

    prompt = (
        f"A user ran AI training on GPU {gpu_name} for {hours} hours in {region}.\n"
        f"The estimated CO2 emissions are {emissions:.2f} grams.\n"
        "Provide actionable recommendations to reduce the carbon footprint."
    )

    try:
        response = co.generate(
            model="command-xlarge-nightly",   # You can also use "command-r" or "command-light"
            prompt=prompt,
            max_tokens=200,
            temperature=0.7
        )
        text = response.generations[0].text
        return text.strip()
    except Exception as e:
        # Fallback recommendations if model fails
        return (
            "Use GPUs with lower power consumption, run training during off-peak hours, "
            "and optimize your code to shorten training time."
        )

# ----------------------
# Regression & Plotting
# ----------------------
def project_emissions_graph_batch(devices_data):
    """
    devices_data: list of dicts with keys:
        'name', 'past_hours', 'past_emissions', 'future_hours'
    Returns a professional multi-line regression graph and summary text.
    """
    fig, ax = plt.subplots(figsize=(10,6))
    colors = plt.cm.tab10.colors  # professional color palette
    summary = ""

    for i, dev in enumerate(devices_data):
        name = dev['name']
        past_hours = np.array(dev['past_hours']).reshape(-1,1)
        past_emissions = np.array(dev['past_emissions'])
        future_hours = np.array(dev['future_hours']).reshape(-1,1)

        # Fit regression
        model = LinearRegression()
        model.fit(past_hours, past_emissions)

        # Predict
        all_hours = np.vstack([past_hours, future_hours])
        predictions = model.predict(all_hours)

        # Plot
        ax.plot(past_hours, past_emissions, 'o', color=colors[i%10], label=f"{name} Past")
        ax.plot(all_hours, predictions, '-', color=colors[i%10], linewidth=2, label=f"{name} Predicted")

        # Add to summary
        summary += f"{name} Predictions:\n"
        for h, e in zip(future_hours.flatten(), predictions[-len(future_hours):]):
            summary += f"{h} hrs → {e:.2f} g CO2\n"
        summary += "\n"

    ax.set_xlabel("Training Hours")
    ax.set_ylabel("CO2 Emissions (g)")
    ax.set_title("AI Training Emissions Prediction (Multiple Devices)")
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.legend()
    ax.legend()
    plt.tight_layout()
    plt.show()  # <- this makes the plot window appear
    return summary, fig

